# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6362ebfda48490579996d283502d29127b2df50602a792d9355d8b91911e7bff9c34041787c9088d227ea53ba15c0f2d7f544e4890398440ada2e844b711e050

test:
  secret_key_base: 6d80f1d51d02dc4efd196ac3c98577afc4a53e9a1ddd95e58196579eb7df5e1df9c9c8697f48633ab7dd287987f10a090aa2b1132c08c99a09d45f46452a60a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
